/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.7).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Tweets;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-08-17T18:27:50.720Z")

@Api(value = "tweets", description = "the tweets API")
public interface TweetsApi {

    @ApiOperation(value = "Consulta de usuários", nickname = "tweetsCountGet", notes = "", response = Tweets.class, tags={ "tweets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operação realizada com sucesso", response = Tweets.class),
        @ApiResponse(code = 400, message = "Requisição inválida"),
        @ApiResponse(code = 500, message = "Erro interno") })
    @RequestMapping(value = "/tweets/count",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Tweets> tweetsCountGet(@NotNull @ApiParam(value = "Filtro", required = true, allowableValues = "perHour, perHashtagLangAndLocation") @Valid @RequestParam(value = "filter", required = true) String filter);

}
